### ISSUE TITLE
paper-menu-button is misplaced when used inside any element that has its own layer.

### ISSUE THREAD

**Issue by blasten** [PolymerElements/paper-menu-button#22]
Moved from https://github.com/PolymerElements/paper-drawer-panel/issues/91

The issue can be seen here:  http://jsbin.com/vudafotada/edit?html,output  `position:fixed` is relative to closest positioned containing element if any of the ancestor has its own composite layer.  The current implementation assumes that `position: fixed` is always relative to the viewport.  

* transform and will-change are just a few of the properties that will cause this issue. :(

**Comment by devinivy** [comment]
I think this issue can be attributed to the iron-dropdown element, which is responsible for its positioning.  Also likely related to the issue described here: https://github.com/PolymerElements/paper-menu-button/issues/9#issuecomment-130083499

**Comment by realiztiK** [comment]
Correct, the dropdown has miscalculated values for css positioning attributes right, left, top and z-index

**Comment by aydun1** [comment]
I believe this issue is related.

In Safari, the dropdown menus in paper-scroll-header-panel at first work fine:
https://www.aidan.in/headermenu.html

However, if you scroll down and back up, the dropdowns are misplaced. If you inspect them, the blue box overlays are in the correct position, however the dropdown itself is horizontally offset off the screen. In this instance it only seems to be affecting the dropdown on the right. 

Sometimes this would only happen when navigating to an anchor and scrolling up.
https://www.aidan.in/headermenu.html#bottom

Only happens in Safari (desktop and mobile), works fine in other browsers.

**Comment by a4xrbj1** [comment]
Is this the same wrong behavior you're talking about? It was working fine in paper-menu v 1.0.1 but when  I upgraded to latest last night it the menu jumped to the middle of the screen:
![polymer iron-icon menu](https://cloud.githubusercontent.com/assets/13525267/11084709/8ba63410-8879-11e5-9622-2ba1b46199f9.gif)

As soon as I reverted the updated all was fine again.

**Comment by cdata** [comment]
I'm going to close this, since the appropriate tracking issue is here: https://github.com/PolymerElements/iron-fit-behavior/issues/33
