### ISSUE TITLE
paper-items visible during page load

### ISSUE THREAD

**Issue by eximius313** [PolymerElements/paper-menu-button#59]
When you reload a page that is using paper-menu-button all ```paper-item``` elements are visible to the user and cause repositioning of containing div:
![polymer_bug 2](https://cloud.githubusercontent.com/assets/5578017/12708603/624c0708-c8a1-11e5-87ea-9fddb5cb967d.gif)

**Comment by notwaldorf** [comment]
Can you provide a jsbin with repro steps, please? Check this element's [CONTRIBUTING.md](../CONTRIBUTING.md) for an example to help you get started.

**Comment by cdata** [comment]
Hi, this is because the Custom Elements containing the menu have not been upgraded yet. In Firefox, this upgrade will happen asynchronously relative to first paint, due to the fact that Firefox must use the Web Components polyfill. A workaround is to put the `unresolved` attribute on your `<body>` tag, e.g.,

```html
<body unresolved>
  <!-- rest of your app -->
</body>
```

If you do this, Polymer will give you a nice transition-in at a point at which most Custom Elements will have been upgraded.

Please re-open if this does not help!
